### ISSUE TITLE
Use GitHub Releases to store the module zip

### ISSUE THREAD

**Issue by yuchi** [sttts/ti-exit#2]
Could you please `git tag` your source and add the [releases](https://github.com/blog/1547-release-your-software) so we can download this module from [gitTio](http://gitt.io/component/com.sttts.exit)?

You can have more information [here on gitTio documentation](http://gitt.io/contributors).

**Comment by sttts** [comment]
For the moment I didn't continue when "ti build" complained that the i386 cannot be found. If you can give me a hint how to compile it in a way that this works... (never did a ti module before).

**Comment by sttts** [comment]
Works fine now. Release zip is uploaded.
